language: ruby

cache: bundler

before_script:
  - psql -c 'create database elixirss_test;' -U postgres || true
  - make install
  - bundle exec rubocop .

rvm:
  - 2.3.1

services:
  - postgresql

after_success:
  bundle exec codeclimate-test-reporter

addons:
  postgresql: "9.6"
