version: "2"

services:
  db:
    image: postgres:9.5
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  app:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -b "0.0.0.0" -p 3000
    environment:
      - EMILITO_DATABASE_HOST=db
    volumes:
      - .:/emilito
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec sidekiq
    environment:
      - EMILITO_DATABASE_HOST=db
    volumes:
      - .:/emilito
      - bundle:/bundle
    depends_on:
      - db
      - redis

volumes:
  bundle:
  postgres:
  redis:
